---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu1804-ansible
    tmpfs:
      - /run
      - /tmp
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
